### ISSUE TITLE
resume crawlers where left off last time , CLI mode

### ISSUE THREAD

**Issue by satyam575** [fhamborg/news-please#112]
If I run news-please for 5 hours and then shut it down using Ctrl+c ,an entry is created in .resume-job folder . I wanted to know ,if I run news-please again from cmd will it start where it left off last time . 
- Does it keep track of articles it has already seen ? ( in requests.queue/request.seen/spider.state)
- Will i be scraping the same 5gbs of data first before i start scraping news articles ?  
   couldn't figure out in the wiki .
- Also , it will be helpfull if you could shed light on resume-jobs folder

 Thanks

**Comment by fhamborg** [comment]
Regarding the ability to resume jobs, news-please relies 100% on scrapy's resuming functionality; scrapy is also the library creating the `.resume-job` folder. We haven't tested that functionality in-depth, so unfortunately I cannot give you very reliable information on that. As far as I remember, scrapy retains information on which pages, i.e. articles, have been crawled already (your first question Q1), so that I'd assume they would not be crawled another time (except if you configured news-please to do so). Same goes for Q2, my assumption would be no.

**Comment by fhamborg** [comment]
Do you have gained insights on your questions in the meantime yourself? We'd be happy to hear about it! :-)
