### ISSUE TITLE
When crawling whole sites, is there a way to start crawling the latest news rather than old ones?

### ISSUE THREAD

**Issue by justlike-prog** [fhamborg/news-please#185]
**Mandatory**
* [ x] I read the documentation ([readme](https://github.com/fhamborg/news-please/blob/master/README.md) and [wiki](https://github.com/fhamborg/news-please/wiki)).
* [ x] I searched other issues (including closed issues) and could not find any to be related. If you find related issues post them below or directly add your issue to the most related one.

**Describe your question**
When I scrape wholes sites, the crawler starts few years back. Does the crawler have a more intelligent way to crawling info and starting with more recent news? I already filter out by date, but it can take ages to get all the news, since the crawler always starts with articles posted a few years ago. 

**Intent (optional; we'll use this info to prioritize upcoming tasks to work on)**
* [x ] personal
* [ ] academic
* [ ] business
* [ ] other
* Some information on your project:

**Comment by fhamborg** [comment]
Which crawler did you use? Currently, there seems to be no easy (=quick) and reliable way to determine from when a news article is without fully parsing it.

**Comment by crecord** [comment]
I ran into this issue. I was working with some RSS feeds that had so many links that the script would run over a day, just on one source. 

It's not a perfect solution, but I am now using the [CLOSESPIDER_PAGECOUNT](https://doc.scrapy.org/en/1.1/topics/extensions.html#std:setting-CLOSESPIDER_PAGECOUNT) scrapy setting in my config file to cap the number of articles that can be processed per source. 

It's not a perfect solution, because it will miss over some potentially relevant entries. But it's quick and worked for my purposes and with most of my sources.
