### ISSUE TITLE
ImportError: No module named _thread

### ISSUE THREAD

**Issue by AjayS91** [fhamborg/news-please#21]
>>> import newsplease
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/hi-161/home/nes/ajay/local/lib/python2.7/site-packages/newsplease/__init__.py", line 6, in <module>
    from newsplease.single_crawler import SingleCrawler
  File "/home/hi-161/home/nes/ajay/local/lib/python2.7/site-packages/newsplease/single_crawler.py", line 26, in <module>
    from _thread import start_new_thread
ImportError: No module named _thread

**Comment by fhamborg** [comment]
the problem here is that the _thread package (Python 3.x) is named simply thread in Python 2.7. I will fix this in the next couple of days, until then you could do the following:

1. open /home/hi-161/home/nes/ajay/local/lib/python2.7/site-packages/newsplease/single_crawler.py
2. replace _thread by thread

should work then

**Comment by fhamborg** [comment]
i already fixed it in the code, but its not available on pypi yet.

**Comment by AjayS91** [comment]
@fhamborg thanks a lot  :+1:

**Comment by fhamborg** [comment]
I have updated the PyPI package. You can just perform an update or probably safer would be to uninstall and reinstall news-please.
```
pip uninstall news-please
pip install news-please
```
