### ISSUE TITLE
Cut down on what is published per article

### ISSUE THREAD

**Issue by DenymW** [fhamborg/news-please#23]
Hi guys, love the tool, I was just looking for a way to cut down on the fields written to file and change the field names. Is there a file where I can edit these settings?

specifically I want to make it so the ouput files only contain:

'url': {'type': 'string', 'index': 'not_analyzed'},
    'source': {'type': 'string', 'index': 'not_analyzed'},
    'created_at#(renamed published_date)#': {'type': 'date', "format":"yyyy-MM-dd HH:mm:ss"},
    'title': {'type': 'string'},
    'text': {'type': 'string'},
    'author': {'type': 'string'}

**Comment by fhamborg** [comment]
Hi,
a clean and general solution (that I would add to the project) would allow to map the fields we internally use to fields that are exported to the JSON file. Unfortunately, I cannot add this feature due to a lack of time currently. So, to address your issue, there are two options: (1) Change the export according to your needs. You can do that very easily in the pipelines.py file in the function extract_relevant_info() (line 273). (2) Add the above yourself (the general, configurable mapping) and create a pull request, and I'll gladly merge that into the master branch.
Best,
Felix
