### ISSUE TITLE
Problem with using ElasticSeach

### ISSUE THREAD

**Issue by lukaskawerau** [fhamborg/news-please#29]
I have installed [this](https://store.docker.com/community/images/sebp/elk) docker image on my Mac, and it starts fine. Nothing changed configuration-wise.

When I run news-please, however, I get the following error:
`[newsplease.config:163|INFO] Loading config-file (/Users/lukaskawerau/news-please-repo/config/config.cfg)
[newsplease.config:163|INFO] Loading config-file (/Users/lukaskawerau/news-please-repo/config/config.cfg)
[newsplease.config:163|INFO] Loading config-file (/Users/lukaskawerau/news-please-repo/config/config.cfg)
[newsplease.config:163|INFO] Loading config-file (/Users/lukaskawerau/news-please-repo/config/config.cfg)
Unhandled error in Deferred:

Unhandled error in Deferred:

Unhandled error in Deferred:

[newsplease.__main__:270|INFO] Graceful stop called manually. Shutting down.`

Is there anything, any steps I'm missing to get news-please to run with ES?
Running it with basic json/html-export works fine.

Any help appreciated!

**Comment by fhamborg** [comment]
Which python version are you using? And also which news-please version?

**Comment by lukaskawerau** [comment]
Python 3.5 in a conda env. The current version that's on pip.

**Comment by fhamborg** [comment]
I cannot reproduce the `Unhandled error in Deffered` problem that you got, but noticed a typo in the README.md. So, if you exactly followed the README.md news-please should crash with another error message. The fix for that issue is to write `newsplease.pipeline.pipelines.ElasticsearchStorage` instead of `newsplease.pipeline.pipelines.ElasticSearchStorage`. Let me know if that solves your current problem.

**Comment by lukaskawerau** [comment]
Yes, that fixes it, thanks!
