### ISSUE TITLE
Can't run example

### ISSUE THREAD

**Issue by ivan-geentilal** [fhamborg/news-please#54]
Hello, I am trying to work out with the examples. 

I installed it, simply running "pip install newsplease.zip" 

After that I am running python downloadfromurl.py and am getting the following error:

Traceback (most recent call last):
  File "downloadfromurl.py", line 16, in <module>
    with open(basepath + article['filename'] + '.json', 'w') as outfile:
TypeError: 'NewsArticle' object is not subscriptable`
 
I change basepath and url.  

What am I missing? `

**Comment by aamin3** [comment]
hello- was this issue resolved?

**Comment by norberte** [comment]
Whoever closed this issue should put an explanation to how this was resolved. I am getting the same issue as well, and I would like to know how to solve it.

**Comment by fhamborg** [comment]
Hi, as stated in the [readme](https://github.com/fhamborg/news-please/blob/master/README.md#issues) we are only able to process bug reports that use the [bug report template](https://github.com/fhamborg/news-please/issues/new?template=bug_report.md). Issues that do not use the corresponding template usually have to be closed, because not all required information is available to investigate the issue. You are welcome to file a bug report using the template mentioned above.
