### ISSUE TITLE
How to limit the time spend on the same website

### ISSUE THREAD

**Issue by godambrosio** [fhamborg/news-please#56]
Hi first of all I want to thank you for this project.
Now,  I what I need is to limit the time that the spider spend on the same website, for example the last time that I execute it I was having almost 1.5 Gb dowloaded from the same webiste.
For the moment I'm using the configuration by defaults and I only specify the urls for the sites that i want to crawl.

Thank you very much.

**Comment by fhamborg** [comment]
unfortunately, we cannot add such functionality currently. however, if you want to implement this yourself: crawling is performed by scrapy, so you may refer to their documentation and see if scrapy either already supports something like this or implement your own subclass of the class Spider, in order to support this.
