### ISSUE TITLE
Full website extraction via library

### ISSUE THREAD

**Issue by tsoernes** [fhamborg/news-please#74]
Is support for this planned? If not, why not, how much work do you think it would be, and would you accept a PR?

**Comment by fhamborg** [comment]
that's currently not planned. in contrast to the library mode, the full website extraction - since it is likely to deal with much larger amounts of news articles compared to the library mode - is designed to run on much longer time periods, thereby relying on the core functionality of scrapy. the scrapy functionality is, however, not part of the library mode. yet, it's of course possible to integrate the full website extraction functionality into the library mode. in principle we are glad for any support on the project! :-) so feel free to add a PR, which we will then check for compatibility to our architecture decisions.
